import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignIn,
  UserButton,
} from "@clerk/nextjs";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} min-h-screen flex flex-col`}>
          <header className="p-4 flex gap-8 justify-end items-center bg-primary-dark">
            <Link
              href="/create-note"
              className="text-sm text-white hover:text-semibold hover:text-primary-light transition-all"
            >
              Create Note
            </Link>
            <SignedOut>
              <Link
                href="/sign-in"
                className="text-sm text-white hover:text-semibold hover:text-primary-light transition-all"
              >
                Sign in
              </Link>
            </SignedOut>
            <UserButton />
          </header>
          <main className="flex flex-col justify-center items-center flex-1">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
